name: Run

on:
  push:
    branches:
      - main

jobs:
  build-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t kotlin-simple-project .
      - name: Exec kotlin program
        run: docker run --rm --name kotlin-simple-project kotlin-simple-project
